export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_PASS = "LOGIN_PASS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT_PASS = "LOGOUT_PASS";

export const FETCH_LISTS_INIT = "FETCH_LISTS_INIT";
export const FETCH_LISTS_FAIL = "FETCH_LISTS_FAIL";
export const FETCH_LISTS_PASS = "FETCH_LISTS_PASS";

export const CREATE_LIST_PASS = "CREATE_LIST_PASS";
export const CREATE_LIST_INIT = "CREATE_LIST_INIT";
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL";

export const REMOVE_LIST_INIT = "REMOVE_LIST_INIT";
export const REMOVE_LIST_FAIL = "REMOVE_LIST_FAIL";
export const REMOVE_LIST_PASS = "REMOVE_LIST_PASS";


export const CLEAR_REDIRECT_ID = "CLEAR_REDIRECT_ID";


export const CREATE_ITEM_INIT = "CREATE_ITEM_INIT";
export const REMOVE_ITEM_INIT = "REMOVE_ITEM_INIT";
export const TOGGLE_ITEM_INIT = "TOGGLE_ITEM_INIT";
export const UPDATE_ITEM_INIT = "UPDATE_ITEM_INIT";

export const CREATE_ITEM_PASS = "CREATE_ITEM_PASS";

export const CREATE_ITEM_FAIL = "CREATE_ITEM_FAIL";
export const REMOVE_ITEM_FAIL = "REMOVE_ITEM_FAIL";
export const TOGGLE_ITEM_FAIL = "TOGGLE_ITEM_FAIL";
export const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL";

export const CLEAR_LISTS_ERROR = "CLEAR_LISTS_ERROR";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";

export const SHOW_ERROR_DIV = "SHOW_ERROR_DIV";
export const HIDE_ERROR_DIV = "HIDE_ERROR_DIV";
