export const LOGIN_PASS = "LOGIN_PASS";
export const LOGOUT_PASS = "LOGOUT_PASS";

export const FETCH_LISTS_PASS = "FETCH_LISTS_PASS";


export const CREATE_LIST_PASS = "CREATE_LIST_PASS";
export const REMOVE_LIST_INIT = "REMOVE_LIST_INIT";
export const REMOVE_LIST_FAIL = "REMOVE_LIST_FAIL";


export const CREATE_ITEM_PASS = "CREATE_ITEM_PASS";
export const TOGGLE_ITEM_INIT = "TOGGLE_ITEM_INIT";
export const TOGGLE_ITEM_FAIL = "TOGGLE_ITEM_FAIL";
export const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL";
export const UPDATE_ITEM_INIT = "UPDATE_ITEM_INIT";
export const REMOVE_ITEM_INIT = "REMOVE_ITEM_INIT";
export const REMOVE_ITEM_FAIL = "REMOVE_ITEM_FAIL";



export const SHOW_ERROR_DIV = "SHOW_ERROR_DIV";
export const HIDE_ERROR_DIV = "HIDE_ERROR_DIV";
